name: test
on:
  workflow_dispatch:

jobs:
   change:
    name: Change Request
    runs-on: ubuntu-latest
    steps:     
      - name: ServiceNow DevOps Change Attributes
        uses: ServiceNow/servicenow-devops-change@dev
        with:
          devops-integration-user-name: ${{ secrets.SN_DEVOPS_USER }}
          devops-integration-user-password: ${{ secrets.SN_DEVOPS_PASSWORD }}
          # devops-integration-token: ${{ secrets.SN_DEVOPS_TOKEN }}
          instance-url: ${{ secrets.SN_INSTANCE_URL }}
          tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
          context-github: ${{ toJSON(github) }}
          job-name: 'Change Request'
          change-request: '{ "autoCloseChange": true,"attributes":{"short_description":"Automated Software Deployment","chg_model":"007c4001c343101035ae3f52c1d3aeb2","description":"Automated Software Deployment.","assignment_group":"a715cd759f2002002920bde8132e7018","implementation_plan":"Software update is tested and results can be found in Test Summaries Tab; When the change is approved the implementation happens automated by the CICD pipeline within the change planned start and end time window.","backout_plan":"When software fails in production, the previous software release will be re-deployed.","test_plan":"Testing if the software was successfully deployed"}}'
          interval: '100'
          timeout: '3600'
          deployment-gate: '{"environment":"prod","jobId":"deploy","jobName":"Deploy"}'
  # change:
  #    name: ServiceNow DevOps Change
  #    runs-on: ubuntu-latest
  #    outputs:
  #     change-request-number: ${{ steps.change.outputs.change-request-number }}
  #    steps:
  #       - name: ServiceNow DevOps Change Attributes
  #         uses: ServiceNow/servicenow-devops-change@v4.1.0
  #         with:
  #            devops-integration-token: ${{ secrets.SN_DEVOPS_INTEGRATION_TOKEN }}
  #            instance-url: ${{ secrets.SN_INSTANCE_URL }}
  #            tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
  #            context-github: ${{ toJSON(github) }}
  #            job-name: 'ServiceNow DevOps Change'
  #            change-request: '{"setCloseCode":"true","autoCloseChange":true,"attributes":{"short_description":"Automated Software Deployment","description":"Automated Software Deployment.","assignment_group":"a715cd759f2002002920bde8132e7018","implementation_plan":"Software update is tested and results can be found in Test Summaries Tab; When the change is approved the implementation happens automated by the CICD pipeline within the change planned start and end time window.","backout_plan":"When software fails in production, the previous software release will be re-deployed.","test_plan":"Testing if the software was successfully deployed"}}'
  #            interval: '100'
  #            timeout: '3600'
  #            #deployment-gate: '{"environment":"production","jobName":"Deploy"}'
             
   deploy:
     name: Deploy
     environment: production
     needs: change
     runs-on: ubuntu-latest
     steps:
       - name: test
         run: echo true
